language: java
rvm: 2.4

addons:
  apt:
    packages:
    - ant-optional

branches:
  only:
  - fb1

before_script: script/ci

script:
- ant test/junit/backend
- ant test/junit/command
- ant test/junit/data
- ant test/junit/jobs
- ant test/junit/util
- ant test/junit/ComparatorTests.java
- ant test//junit/UtilTests.java
- ant css jspc
