#!/bin/bash
# Author: Tyler Jensen
# =========================
# DESCRIPTION: Pulls down starexec trunk, builds it with ant, packages it into a war and deploys it to the server. 
# =========================
#

WEB_HOME=/project/tomcat-webapps/webapps
BACKUP_HOME=$WEB_HOME/backup
NEW_DIR=$BACKUP_HOME/`date +%m%d%y%s`  
STAR_HOME=/home/starexec
STAR_TEMP=/home/starexec/temp
WAR=starexec.war
STAR_WAR=$WEB_HOME/$WAR
SVN_URL=''

# Setup the branch the user wants to pull from
if [ "$1" == "-trunk" ]; then
	SVN_URL='https://svn.divms.uiowa.edu/repos/clc/projects/starexec/dev/trunk'
else
	if [ "$1" == "-fb1" ]; then
		SVN_URL='https://svn.divms.uiowa.edu/repos/clc/projects/starexec/dev/branches/fb1'
	else
		if [ "$1" == "-fb2" ]; then
			SVN_URL='https://svn.divms.uiowa.edu/repos/clc/projects/starexec/dev/branches/fb2'
		else
			echo "please specify a repository to use [-trunk, -fb1, -fb2]"
			exit 0
		fi
	fi
fi

echo Clearing temp directory: $STAR_TEMP
rm -rf $STAR_TEMP

# Pull the trunk into the temp folder
echo Pulling starexec trunk, please use your DIVMS credentials
svn co $SVN_URL $STAR_TEMP -q

echo Starting ANT build process...
cd $STAR_TEMP/starexec
ant -buildfile build.xml -q
echo Starexec compilation and configuratio SUCCESSFUL

echo Moving existing war file: $STAR_WAR
#rm -f $STAR_WAR
mkdir $NEW_DIR
mv $STAR_WAR $NEW_DIR/starBackup.war

echo Waiting for tomcat to move previous starexec version
while [ -e "$STAR_WAR" ]
do
	sleep 1s
	echo -n '.'
done

echo Copying new WAR to $WEB_HOME
cp $STAR_TEMP/starexec/$WAR $WEB_HOME/$WAR

echo Changing permissions on $STAR_WAR
chmod 775 $STAR_WAR

# Restarting tomcat will explode the starexec.war into a webapp
echo Restarting Tomcat, please use your DIVMS credentials...
sudo /sbin/service tomcat7 restart

echo Cleaning up $STAR_TEMP
rm -rf $STAR_TEMP

echo Starexec production deployment SUCCESSFUL
echo Please manually update the database as needed. Schema and stored procedure updates are not included in this deployment
