#!/bin/bash
# Deletes any pending jobs and clears the queues of any error codes

# Remove and pending or executing jobs
qdel -u tomcat
qdel -u bmccune
qdel -u sandbox

# Clear errors from the cluster
qmod -c all.q
qmod -c star1.q
qmod -c star2.q
qmod -c star3.q
qmod -c star4.q

echo "grid engine cleaned"
