#!/bin/bash
# Deletes any pending jobs and clears the queues of any error codes

# Remove and pending or executing jobs
sudo -u sgeadmin -i qdel -u tomcat
sudo -u sgeadmin -i qdel -u bmccune
sudo -u sgeadmin -i qdel -u sandbox

# Clear errors from the cluster
sudo -u sgeadmin -i qmod -c all.q
sudo -u sgeadmin -i qmod -c star1.q
sudo -u sgeadmin -i qmod -c star2.q
sudo -u sgeadmin -i qmod -c star3.q
sudo -u sgeadmin -i qmod -c star4.q

echo "grid engine cleaned"
