#!/bin/bash
# The queue to submit to
#$ -q $$QUEUE$$
#OAR -q $$QUEUE$$
#OAR -p queue='$$QUEUE$$'


# Submit under sandbox user 
#$ -u sandbox

# Resource limits
#$ -l s_fsize=$$MAX_WRITE$$G,slots=$$SLOTS$$,h=$$NODE_NAME$$

# Default shell is bash
#$ -S /bin/bash

# Make these jobs high priority
#$ -p 1024

# Merge stdout and stderr streams
#$ -j y

WORKING_DIR_BASE='$$WORKING_DIR_BASE$$'


echo "deleting solver cache on $$NODE_NAME$$"

rm -rf "$WORKING_DIR_BASE/solvercache"
mkdir "$WORKING_DIR_BASE/solvercache"
chmod gu+rwx "$WORKING_DIR_BASE/solvercache"

# doing ls to confirm the directory was removed
ls -l "$WORKING_DIR_BASE/solvercache"

echo "cache script ending."

