#!/bin/bash
#==========================================================================
# Standard SGE job script setup.
#==========================================================================

# The queue to submit to
#$ -q $$QUEUE$$

# Request exclusive access
#$ -l excl=false

# Enable resource limit signals
#$ -notify

# Submit under sandbox user 
#$ -u sandbox

# Resource limits
#$ -l s_fsize=$$MAX_WRITE$$G 

# we are using runsolver now instead of giving these to SGE: -l s_vmem=$$MAX_MEM$$G -l s_rt=$$MAX_RUNTIME$$ -l s_cpu=$$MAX_CPUTIME$$

# Default shell is bash
#$ -S /bin/bash

# Merge stdout and stderr streams
#$ -j y

# Variables in local environment.  Note that SOLVER_NAME, SOLVER_PATH, and BENCH_PATH are base64 encoded (we will decode in the prolog)
#$ -v JOB_STAR_ID='$$JOBID$$',PAIR_OUTPUT_DIRECTORY='$$PAIR_OUTPUT_DIRECTORY$$',PAIR_OUTPUT_PATH='$$PAIR_OUTPUT_PATH$$',RAND_SEED='$$RANDSEED$$',PRE_PROCESSOR_PATH='$$PRE_PROCESSOR_PATH$$',MAX_MEM='$$MAX_MEM$$',POST_PROCESSOR_PATH='$$POST_PROCESSOR_PATH$$',USER_ID='$$USERID$$',HAS_DEPENDS='$$HAS_DEPENDS$$',SOLVER_PATH='$$SOLVER_PATH$$',SOLVER_NAME='$$SOLVER_NAME$$',CONFIG_NAME='$$CONFIG$$',BENCH_PATH='$$BENCH$$',PAIR_ID='$$PAIRID$$',STAREXEC_MAX_MEM='$$MAX_MEM$$',STAREXEC_MAX_WRITE='$$MAX_WRITE$$',STAREXEC_CPU_LIMIT='$$MAX_CPUTIME$$',STAREXEC_WALLCLOCK_LIMIT='$$MAX_RUNTIME$$',REPORT_HOST='$$REPORT_HOST$$',DB_NAME='$$DB_NAME$$',SHARED_DIR='$$STAREXEC_DATA_DIR$$',SPACE_PATH='$$SPACE_PATH$$',SOLVER_ID='$$SOLVER_ID$$',SCRIPT_PATH='$$SCRIPT_PATH$$',SOLVER_TIMESTAMP='$$SOLVER_TIMESTAMP$$'

# Include common functions
. /home/starexec/sge_scripts/functions.bash

#==========================================================================
# Signal Traps
#
# These are just for the limits we are asking SGE to enforce.
# For the ones runsolver is enforcing, the epilog will look in the
# watcher.out file.
#==========================================================================

trap "limitExceeded 'file write' $EXCEED_FILE_WRITE" SIGXFSZ


handleUsrTwo() {
	
  echo "Jobscript received USR2."
}

trap 'handleUsrTwo' USR2

#==========================================================================
# Execute (prolog will take care of data staging)
# NOTE: Keep things in here to a MINIMUM. Anything below this line counts
# against the user's execution time
#==========================================================================

findSandbox $PAIR_ID


if [ $SANDBOX -eq 1 ]
then
	cd /export/starexec/sandbox/solver/bin
	pwd
	echo "  $LOCAL_RUNSOLVER_PATH --timestamp --add-eof --cores 0-3 -C $$MAX_CPUTIME$$ -W $$MAX_RUNTIME$$ -M $$MAX_MEM$$  -w $OUT_DIR/watcher.out -v $OUT_DIR/var.out -o $OUT_DIR/stdout.txt $LOCAL_CONFIG_PATH $LOCAL_BENCH_PATH"

	sudo -u sandbox STAREXEC_MAX_MEM=$MAX_MEM STAREXEC_MAX_WRITE=$$MAX_WRITE$$ STAREXEC_CPU_LIMIT=$$MAX_CPUTIME$$ STAREXEC_WALLCLOCK_LIMIT=$$MAX_RUNTIME$$ "$LOCAL_RUNSOLVER_PATH" --timestamp --add-eof --cores 0-3 -C $$MAX_CPUTIME$$ -W $$MAX_RUNTIME$$ -M $MAX_MEM  -w "$OUT_DIR/watcher.out" -v "$OUT_DIR/var.out" -o "$OUT_DIR/stdout.txt" "$LOCAL_CONFIG_PATH" "$LOCAL_BENCH_PATH" 
	
elif [ $SANDBOX -eq 2 ]
then
	cd /export/starexec/sandbox2/solver/bin
	pwd
	echo "  $LOCAL_RUNSOLVER_PATH --timestamp --add-eof --cores 4-7 -C $$MAX_CPUTIME$$ -W $$MAX_RUNTIME$$ -M $$MAX_MEM$$  -w $OUT_DIR/watcher.out -v "$OUT_DIR/var.out" -o $OUT_DIR/stdout.txt $LOCAL_CONFIG_PATH $LOCAL_BENCH_PATH"
	sudo -u sandbox2 STAREXEC_MAX_MEM=$MAX_MEM STAREXEC_MAX_WRITE=$$MAX_WRITE$$ STAREXEC_CPU_LIMIT=$$MAX_CPUTIME$$ STAREXEC_WALLCLOCK_LIMIT=$$MAX_RUNTIME$$ "$LOCAL_RUNSOLVER_PATH" --timestamp --add-eof --cores 4-7 -C $$MAX_CPUTIME$$ -W $$MAX_RUNTIME$$ -M $MAX_MEM  -w "$OUT_DIR/watcher.out" -v "$OUT_DIR/var.out" -o "$OUT_DIR/stdout.txt" "$LOCAL_CONFIG_PATH" "$LOCAL_BENCH_PATH" 

else
	log "no job run for pair $PAIR_ID because a sandbox was not found"
	sendStatus $ERROR_RUNSCRIPT
fi

echo "Jobscript ending."

#==========================================================================
# Complete (epilog will take care or reporting and data saving) 
#==========================================================================
