#!/bin/bash
#==========================================================================
# Standard SGE job script
#==========================================================================

# The queue to submit to
#$ -q $$QUEUE$$

# Request exclusive access
#$ -l excl=true

# Default shell is bash
#$ -S /bin/bash

# Merge stdout and stderr streams
#$ -j y

# Variables in local environment
#$ -v JOB_STAR_ID=$$JOBID$$,JOB_START=Running,JOB_END=Finished,JOB_ERROR=Error

#==========================================================================
# Initialize
#==========================================================================

if [ -x /home/starexec/starjob_fun ]; then
        . /home/starexec/starjob_fun
else
        echo 'Cannot load STAREXEC function file, exiting.'
        exit 1
fi

#==========================================================================
# Execute 
#==========================================================================
# runPair <solver> <config> <benchmark> <pair id>

runPair $$SOLVER$$ $$CONFIG$$ $$BENCH$$ $$PAIRID$$

#==========================================================================
# Complete 
#==========================================================================

if [ $? -eq 0 ]; then
        echo
        echo 'Finished successfully.'
fi