#!/bin/bash
# Hashes a password using a pre-specified hashing algorithm

readonly PASSWORD="$*"
if [[ -z $PASSWORD ]]; then
	echo "Usage:"
	echo "	$0 [Password to hash]"
	exit
fi

readonly HASH=$(echo -n "$PASSWORD" | openssl sha512 -r)
echo "\"$PASSWORD\" hashes to ${HASH/ */}"
